// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgwjwiFrDCax_D8v_B9GWBJjmoKbzf0j0',
    appId: '1:881958868689:android:71f282a0b6427923b2d7f0',
    messagingSenderId: '881958868689',
    projectId: 'dngen-622da',
    databaseURL: 'https://dngen-622da-default-rtdb.firebaseio.com',
    storageBucket: 'dngen-622da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEnucN9mtwSebWSINBld12dN6DC9FnfwI',
    appId: '1:881958868689:ios:23fbc4006fa85b1db2d7f0',
    messagingSenderId: '881958868689',
    projectId: 'dngen-622da',
    databaseURL: 'https://dngen-622da-default-rtdb.firebaseio.com',
    storageBucket: 'dngen-622da.appspot.com',
    iosClientId: '881958868689-0bev7d2e1imki2f9a92afclj8jqklllg.apps.googleusercontent.com',
    iosBundleId: 'com.domain-name-generator.app',
  );
}
